/**
 * VYRDON RootPass - ZK verifier honesty test
 *
 * The current on-chain RootPassVerifier._verifyZKProof returns `false`
 * because no Circom circuit + trusted setup exists yet. The ZK layer is
 * present as a reference artifact, not operationally complete; production
 * ZK capability remains planned.
 *
 * These tests pin that honest state into CI so the repo cannot quietly
 * upgrade from REFERENCE to operational without an explicit change:
 *
 *   1. verifyProof returns valid=false for every submitted proof today.
 *   2. The decision value submitted by the caller is still recorded,
 *      so the contract cannot be claimed to verify on-chain proofs
 *      that it does not actually verify.
 *
 * When a real Groth16 verifier is generated by snarkjs and integrated,
 * these tests must be replaced with positive verification tests against
 * known-good proofs.
 */

import { expect } from "chai";
import { ethers } from "hardhat";

describe("RootPass: ZK verifier honesty (placeholder behavior)", function () {
  async function deploy() {
    const factory = await ethers.getContractFactory("RootPassVerifier");
    const verifier = await factory.deploy();
    await verifier.waitForDeployment();
    return verifier;
  }

  it("verifyProof returns valid=false for the current placeholder verifier", async function () {
    const verifier = await deploy();
    const proof = "0x";
    const publicSignals: bigint[] = [1n]; // pretend a PASS decision
    const [signer] = await ethers.getSigners();

    // Call as a transaction (non-view) so it executes and emits events.
    const tx = await verifier.connect(signer).verifyProof(proof, publicSignals);
    await tx.wait();

    // Read the recorded decision back from storage.
    const [submitter, decision, , , valid] = await verifier.getDecision(0);
    expect(submitter).to.equal(await signer.getAddress());
    expect(decision).to.equal(1n);
    expect(valid).to.equal(false);
  });

  it("rejects an empty publicSignals array (the decision channel must be present)", async function () {
    const verifier = await deploy();
    await expect(verifier.verifyProof("0x", [])).to.be.revertedWith("Missing public signals");
  });

  it("rejects an out-of-range decision value (>2)", async function () {
    const verifier = await deploy();
    await expect(verifier.verifyProof("0x", [3n])).to.be.revertedWith("Invalid decision value");
  });

  it("records every submission, even when valid=false", async function () {
    const verifier = await deploy();
    const [signer] = await ethers.getSigners();
    await (await verifier.connect(signer).verifyProof("0x01", [0n])).wait();
    await (await verifier.connect(signer).verifyProof("0x02", [1n])).wait();
    await (await verifier.connect(signer).verifyProof("0x03", [2n])).wait();
    expect(await verifier.decisionCount()).to.equal(3n);
  });
});
